---
title: "GENESIS workshop 2026"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: smgogarten/GENESIS_workshop_2026
description: "Course materials for Bioconductor Africa: GENESIS workshop 2026"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE)
```

# Introduction

This site contains course materials for Course materials for Biocondoctor Africa: GENESIS workshop on July 22 and 29, 2026.
Data used is located in the [github repository](https://github.com/smgogarten/GENESIS_workshop_2026) from which the site is built.

Slides for lectures are linked below in the schedule.

## Schedule

Background material (not covered in workshop): [GWAS crash course](https://drive.google.com/file/d/1jIAraJ2g4B9iMaw4ADH_lerWic11fxCd/view)

**Wednesday, July 22**

- Introduction and Genomic Data Storage
    - Intro to Genomic Data Storage  ([slides](https://si.biostat.washington.edu/sites/default/files/modules/GDS_intro_2.pdf))
    - Demo - [GDS format in R](https://uw-gac.github.io/SISG_2020/gds-format.html)
- Association tests
    - GENESIS for association tests  ([slides](https://si.biostat.washington.edu/sites/default/files/modules/R_assoc_tests_2.pdf))
    - Demo: intro to association tests - [Association tests in R](https://uw-gac.github.io/SISG_2020/association-tests.html)
    - Demo: aggregate tests [Sliding window tests](https://uw-gac.github.io/SISG_2020/association-tests.html#sliding-window-tests)
    

**Wednesday, July 29**

- Population Structure and Relatedness
    - R packages for PCA and relatedness ([slides](https://si.biostat.washington.edu/sites/default/files/modules/R_kinship_pca_1.pdf))
    - Demo - [Population structure and relatedness in R](https://uw-gac.github.io/SISG_2020/computing-a-grm.html)
- Mixed models
    - Demo - [Mixed models in R](https://uw-gac.github.io/SISG_2020/mixed-models.html)
- Variant annotation
    -Variant annotation  ([slides](https://si.biostat.washington.edu/sites/default/files/modules/variant_annotation_0.pdf))
    - Demo - [Using variant annotation](https://uw-gac.github.io/SISG_2020/variant-annotation.html)



Download the workshop data and exercises: https://github.com/UW-GAC/GENESIS_workshop_2026/archive/main.zip

## R packages used

- [SeqArray](http://bioconductor.org/packages/release/bioc/html/SeqArray.html)
- [SeqVarTools](http://bioconductor.org/packages/release/bioc/html/SeqVarTools.html)
- [GENESIS](http://bioconductor.org/packages/release/bioc/html/GENESIS.html)
- [SNPRelate](http://bioconductor.org/packages/release/bioc/html/SNPRelate.html)
- [TopmedPipeline](https://github.com/UW-GAC/analysis_pipeline/tree/master/TopmedPipeline)
- [tidyverse](https://www.tidyverse.org)
- [GGally](https://cran.r-project.org/web/packages/GGally)


## Resources

If you are new to R, you might find the following material helpful:

- [Introduction to R](http://faculty.washington.edu/kenrice/rintro/) 
- Graphics with [ggplot2](https://ggplot2.tidyverse.org/) tutorial
- Data manipulation with [dplyr](http://dplyr.tidyverse.org/)
